export const ANSIBLE_ADD_IPADDRESS_REQUEST = "ANSIBLE_ADD_IPADDRESS_REQUEST";
export const ANSIBLE_ADD_IPADDRESS_SUCCESS = "ANSIBLE_ADD_IPADDRESS_SUCCESS";
export const ANSIBLE_ADD_IPADDRESS_FAIL = "ANSIBLE_ADD_IPADDRESS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
