export const CISCO_PROVISION_REQUEST = "CISCO_PROVISION_REQUEST";
export const CISCO_PROVISION_SUCCESS = "CISCO_PROVISION_SUCCESS";
export const CISCO_PROVISION_FAIL = "CISCO_PROVISION_FAIL";

export const CISCO_DIAGNOSIS_REQUEST = "CISCO_DIAGNOSIS_REQUEST";
export const CISCO_DIAGNOSIS_SUCCESS = "CISCO_DIAGNOSIS_SUCCESS";
export const CISCO_DIAGNOSIS_FAIL = "CISCO_DIAGNOSIS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
