export const IPPHONE_PROVISION_REQUEST = "IPPHONE_PROVISION_REQUEST";
export const IPPHONE_PROVISION_SUCCESS = "IPPHONE_PROVISION_SUCCESS";
export const IPPHONE_PROVISION_FAIL = "IPPHONE_PROVISION_FAIL";

export const IPPHONE_REBOOT_REQUEST = "IPPHONE_REBOOT_REQUEST";
export const IPPHONE_REBOOT_SUCCESS = "IPPHONE_REBOOT_SUCCESS";
export const IPPHONE_REBOOT_FAIL = "IPPHONE_REBOOT_FAIL";

export const IPPHONE_RESET_REQUEST = "IPPHONE_RESET_REQUEST";
export const IPPHONE_RESET_SUCCESS = "IPPHONE_RESET_SUCCESS";
export const IPPHONE_RESET_FAIL = "IPPHONE_RESET_FAIL";

export const IPPHONE_FIRMWARE_REQUEST = "IPPHONE_FIRMWARE_REQUEST";
export const IPPHONE_FIRMWARE_SUCCESS = "IPPHONE_FIRMWARE_SUCCESS";
export const IPPHONE_FIRMWARE_FAIL = "IPPHONE_FIRMWARE_FAIL";

export const IPPHONE_STATUS_REQUEST = "IPPHONE_STATUS_REQUEST";
export const IPPHONE_STATUS_SUCCESS = "IPPHONE_STATUS_SUCCESS";
export const IPPHONE_STATUS_FAIL = "IPPHONE_STATUS_FAIL";

export const IPPHONE_HISTORY_REQUEST = "IPPHONE_HISTORY_REQUEST";
export const IPPHONE_HISTORY_SUCCESS = "IPPHONE_HISTORY_SUCCESS";
export const IPPHONE_HISTORY_FAIL = "IPPHONE_HISTORY_FAIL";

export const IPPHONE_TIMESCHEDULE_REQUEST = "IPPHONE_TIMESCHEDULE_REQUEST";
export const IPPHONE_TIMESCHEDULE_SUCCESS = "IPPHONE_TIMESCHEDULE_SUCCESS";
export const IPPHONE_TIMESCHEDULE_FAIL = "IPPHONE_TIMESCHEDULE_FAIL";

export const IPPHONE_FAULT_REQUEST = "IPPHONE_FAULT_REQUEST";
export const IPPHONE_FAULT_SUCCESS = "IPPHONE_FAULT_SUCCESS";
export const IPPHONE_FAULT_FAIL = "IPPHONE_FAULT_FAIL";

export const IPPHONE_SYNC_REQUEST = "IPPHONE_SYNC_REQUEST";
export const IPPHONE_SYNC_SUCCESS = "IPPHONE_SYNC_SUCCESS";
export const IPPHONE_SYNC_FAIL = "IPPHONE_SYNC_FAIL";

export const IPPHONE_FILEUPLOAD_REQUEST = "IPPHONE_FILEUPLOAD_REQUEST";
export const IPPHONE_FILEUPLOAD_SUCCESS = "IPPHONE_FILEUPLOAD_SUCCESS";
export const IPPHONE_FILEUPLOAD_FAIL = "IPPHONE_FILEUPLOAD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
