export const LINUX_REBOOT_REQUEST = "LINUX_REBOOT_REQUEST";
export const LINUX_REBOOT_SUCCESS = "LINUX_REBOOT_SUCCESS";
export const LINUX_REBOOT_FAIL = "LINUX_REBOOT_FAIL";

export const LINUX_PROVISION_REQUEST = "LINUX_PROVISION_REQUEST";
export const LINUX_PROVISION_SUCCESS = "LINUX_PROVISION_SUCCESS";
export const LINUX_PROVISION_FAIL = "LINUX_PROVISION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";