export const SERVER_STATUS_REQUEST = "SERVER_STATUS_REQUEST";
export const SERVER_STATUS_SUCCESS = "SERVER_STATUS_SUCCESS";
export const SERVER_STATUS_FAIL = "SERVER_STATUS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";